-----------------------------------------------------------------------------
INSERT INTO COMMON_NAME([NAME]) VALUES('Villous waterclover');
INSERT INTO COMMON_NAME([NAME]) VALUES('Yellow Hibiscus');
INSERT INTO COMMON_NAME([NAME]) VALUES('White Kauai Rosemallow');
INSERT INTO COMMON_NAME([NAME]) VALUES('Black-fruited Coprosma');
INSERT INTO COMMON_NAME([NAME]) VALUES('Oceanblue Morning Glory');
INSERT INTO COMMON_NAME([NAME]) VALUES('Cat''s claw');
INSERT INTO COMMON_NAME([NAME]) VALUES('Dune Tetramolopium');
INSERT INTO COMMON_NAME([NAME]) VALUES('Indian Tulip Tree');
INSERT INTO COMMON_NAME([NAME]) VALUES('Mexican Primrose Willow');
-----------------------------------------------------------------------------
----New----------------------------------------------------------------------
INSERT INTO COMMON_NAME([NAME]) VALUES('Old World Forkedfern');
INSERT INTO COMMON_NAME([NAME]) VALUES('Hoary Abutilon');
INSERT INTO COMMON_NAME([NAME]) VALUES('Red Abutilon');
INSERT INTO COMMON_NAME([NAME]) VALUES('Hidden-petaled Abutilon');
INSERT INTO COMMON_NAME([NAME]) VALUES('Green-flowered Abutilon');
INSERT INTO COMMON_NAME([NAME]) VALUES('Dwarf Koa');
INSERT INTO COMMON_NAME([NAME]) VALUES('Achyranthes');
INSERT INTO COMMON_NAME([NAME]) VALUES('Black Maidenhair');
INSERT INTO COMMON_NAME([NAME]) VALUES('Oʻahu Wormwood');
INSERT INTO COMMON_NAME([NAME]) VALUES('Maui Wormwood');
INSERT INTO COMMON_NAME([NAME]) VALUES('Birds-nest Fern');
INSERT INTO COMMON_NAME([NAME]) VALUES('Menzies'' Astelia');
INSERT INTO COMMON_NAME([NAME]) VALUES('Baby tears');
INSERT INTO COMMON_NAME([NAME]) VALUES('Koʻolau Range Beggarticks');
INSERT INTO COMMON_NAME([NAME]) VALUES('Cosmosflower Beggarticks');
INSERT INTO COMMON_NAME([NAME]) VALUES('Bulrush');
INSERT INTO COMMON_NAME([NAME]) VALUES('Hawaiian Bonamia');
INSERT INTO COMMON_NAME([NAME]) VALUES('Cabbage-on-a-Baseball-Bat');
INSERT INTO COMMON_NAME([NAME]) VALUES('Molokaʻi ʻōhāhā');
INSERT INTO COMMON_NAME([NAME]) VALUES('Lavafield Jackbean');
INSERT INTO COMMON_NAME([NAME]) VALUES('Caper Bush');
INSERT INTO COMMON_NAME([NAME]) VALUES('Hawaiʻi Sedge');
INSERT INTO COMMON_NAME([NAME]) VALUES('Menyen''s Carex');
INSERT INTO COMMON_NAME([NAME]) VALUES('Agrimony Sandbur');
INSERT INTO COMMON_NAME([NAME]) VALUES('Broadleaf Papala');
INSERT INTO COMMON_NAME([NAME]) VALUES('Hawaiian Goosefoot');
INSERT INTO COMMON_NAME([NAME]) VALUES('Chaisso''s tree fern');
-----------------------------------------------------------------------------